/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'passenger' : null } |
  { 'driver' : null };
export interface Location {
  'latitude' : [] | [number],
  'description' : string,
  'longitude' : [] | [number],
}
export interface PayoutRequest {
  'id' : bigint,
  'status' : PayoutStatus,
  'createdAt' : Time,
  'processedAt' : [] | [Time],
  'amount' : bigint,
  'driver' : Principal,
}
export type PayoutStatus = { 'requested' : null } |
  { 'paid' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface TripRequest {
  'id' : bigint,
  'status' : TripStatus,
  'completedAt' : [] | [Time],
  'passenger' : Principal,
  'dropoffLocation' : Location,
  'fare' : [] | [bigint],
  'createdAt' : Time,
  'acceptedAt' : [] | [Time],
  'driver' : [] | [Principal],
  'pickupLocation' : Location,
}
export type TripStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export interface UserProfile {
  'fullName' : string,
  'accountType' : AccountType,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTrip' : ActorMethod<[bigint], undefined>,
  'adminUpdateTripStatus' : ActorMethod<[bigint, TripStatus], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTrip' : ActorMethod<[bigint], undefined>,
  'completeTrip' : ActorMethod<[bigint], undefined>,
  'createTripRequest' : ActorMethod<[Location, Location, bigint], bigint>,
  'getAllDrivers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriverEarnings' : ActorMethod<[], bigint>,
  'getDriverTrips' : ActorMethod<[Principal], Array<TripRequest>>,
  'getOpenTrips' : ActorMethod<[], Array<TripRequest>>,
  'getPassengerTrips' : ActorMethod<[Principal], Array<TripRequest>>,
  'getPayoutHistory' : ActorMethod<[], Array<PayoutRequest>>,
  'getPendingPayouts' : ActorMethod<[], Array<PayoutRequest>>,
  'getTrip' : ActorMethod<[bigint], [] | [TripRequest]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[AccountType, string, string], undefined>,
  'requestPayout' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePayoutStatus' : ActorMethod<[bigint, PayoutStatus], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];