/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TripStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'description' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
});
export const AccountType = IDL.Variant({
  'passenger' : IDL.Null,
  'driver' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'fullName' : IDL.Text,
  'accountType' : AccountType,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const TripRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : TripStatus,
  'completedAt' : IDL.Opt(Time),
  'passenger' : IDL.Principal,
  'dropoffLocation' : Location,
  'fare' : IDL.Opt(IDL.Nat),
  'createdAt' : Time,
  'acceptedAt' : IDL.Opt(Time),
  'driver' : IDL.Opt(IDL.Principal),
  'pickupLocation' : Location,
});
export const PayoutStatus = IDL.Variant({
  'requested' : IDL.Null,
  'paid' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PayoutRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PayoutStatus,
  'createdAt' : Time,
  'processedAt' : IDL.Opt(Time),
  'amount' : IDL.Nat,
  'driver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTrip' : IDL.Func([IDL.Nat], [], []),
  'adminUpdateTripStatus' : IDL.Func([IDL.Nat, TripStatus], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTrip' : IDL.Func([IDL.Nat], [], []),
  'completeTrip' : IDL.Func([IDL.Nat], [], []),
  'createTripRequest' : IDL.Func([Location, Location, IDL.Nat], [IDL.Nat], []),
  'getAllDrivers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriverEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getDriverTrips' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TripRequest)],
      ['query'],
    ),
  'getOpenTrips' : IDL.Func([], [IDL.Vec(TripRequest)], ['query']),
  'getPassengerTrips' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TripRequest)],
      ['query'],
    ),
  'getPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
  'getPendingPayouts' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
  'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(TripRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([AccountType, IDL.Text, IDL.Text], [], []),
  'requestPayout' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePayoutStatus' : IDL.Func([IDL.Nat, PayoutStatus], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TripStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'description' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
  });
  const AccountType = IDL.Variant({
    'passenger' : IDL.Null,
    'driver' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'fullName' : IDL.Text,
    'accountType' : AccountType,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const TripRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : TripStatus,
    'completedAt' : IDL.Opt(Time),
    'passenger' : IDL.Principal,
    'dropoffLocation' : Location,
    'fare' : IDL.Opt(IDL.Nat),
    'createdAt' : Time,
    'acceptedAt' : IDL.Opt(Time),
    'driver' : IDL.Opt(IDL.Principal),
    'pickupLocation' : Location,
  });
  const PayoutStatus = IDL.Variant({
    'requested' : IDL.Null,
    'paid' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PayoutRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PayoutStatus,
    'createdAt' : Time,
    'processedAt' : IDL.Opt(Time),
    'amount' : IDL.Nat,
    'driver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTrip' : IDL.Func([IDL.Nat], [], []),
    'adminUpdateTripStatus' : IDL.Func([IDL.Nat, TripStatus], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTrip' : IDL.Func([IDL.Nat], [], []),
    'completeTrip' : IDL.Func([IDL.Nat], [], []),
    'createTripRequest' : IDL.Func(
        [Location, Location, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllDrivers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriverEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getDriverTrips' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TripRequest)],
        ['query'],
      ),
    'getOpenTrips' : IDL.Func([], [IDL.Vec(TripRequest)], ['query']),
    'getPassengerTrips' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TripRequest)],
        ['query'],
      ),
    'getPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
    'getPendingPayouts' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
    'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(TripRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([AccountType, IDL.Text, IDL.Text], [], []),
    'requestPayout' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePayoutStatus' : IDL.Func([IDL.Nat, PayoutStatus], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };