/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude?: number;
    description: string;
    longitude?: number;
}
export type Time = bigint;
export interface PayoutRequest {
    id: bigint;
    status: PayoutStatus;
    createdAt: Time;
    processedAt?: Time;
    amount: bigint;
    driver: Principal;
}
export interface TripRequest {
    id: bigint;
    status: TripStatus;
    completedAt?: Time;
    passenger: Principal;
    dropoffLocation: Location;
    fare?: bigint;
    createdAt: Time;
    acceptedAt?: Time;
    driver?: Principal;
    pickupLocation: Location;
}
export interface UserProfile {
    fullName: string;
    accountType: AccountType;
    phone: string;
}
export enum AccountType {
    passenger = "passenger",
    driver = "driver"
}
export enum PayoutStatus {
    requested = "requested",
    paid = "paid",
    approved = "approved",
    rejected = "rejected"
}
export enum TripStatus {
    cancelled = "cancelled",
    open = "open",
    completed = "completed",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptTrip(tripId: bigint): Promise<void>;
    adminUpdateTripStatus(tripId: bigint, status: TripStatus): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelTrip(tripId: bigint): Promise<void>;
    completeTrip(tripId: bigint): Promise<void>;
    createTripRequest(pickup: Location, dropoff: Location, fare: bigint): Promise<bigint>;
    getAllDrivers(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDriverEarnings(): Promise<bigint>;
    getDriverTrips(driver: Principal): Promise<Array<TripRequest>>;
    getOpenTrips(): Promise<Array<TripRequest>>;
    getPassengerTrips(passenger: Principal): Promise<Array<TripRequest>>;
    getPayoutHistory(): Promise<Array<PayoutRequest>>;
    getPendingPayouts(): Promise<Array<PayoutRequest>>;
    getTrip(tripId: bigint): Promise<TripRequest | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(accountType: AccountType, fullName: string, phone: string): Promise<void>;
    requestPayout(amount: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePayoutStatus(payoutId: bigint, newStatus: PayoutStatus): Promise<void>;
    updateProfile(fullName: string, phone: string): Promise<void>;
}
import type { AccountType as _AccountType, Location as _Location, PayoutRequest as _PayoutRequest, PayoutStatus as _PayoutStatus, Time as _Time, TripRequest as _TripRequest, TripStatus as _TripStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTrip(arg0);
            return result;
        }
    }
    async adminUpdateTripStatus(arg0: bigint, arg1: TripStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateTripStatus(arg0, to_candid_TripStatus_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateTripStatus(arg0, to_candid_TripStatus_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTrip(arg0);
            return result;
        }
    }
    async completeTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTrip(arg0);
            return result;
        }
    }
    async createTripRequest(arg0: Location, arg1: Location, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTripRequest(to_candid_Location_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Location_n5(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTripRequest(to_candid_Location_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Location_n5(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getAllDrivers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDrivers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDrivers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverEarnings(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverEarnings();
            return result;
        }
    }
    async getDriverTrips(arg0: Principal): Promise<Array<TripRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverTrips(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverTrips(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenTrips(): Promise<Array<TripRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenTrips();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenTrips();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPassengerTrips(arg0: Principal): Promise<Array<TripRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassengerTrips(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassengerTrips(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayoutHistory(): Promise<Array<PayoutRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutHistory();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutHistory();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPayouts(): Promise<Array<PayoutRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPayouts();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPayouts();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrip(arg0: bigint): Promise<TripRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: AccountType, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_AccountType_n33(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_AccountType_n33(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async requestPayout(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPayout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPayout(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePayoutStatus(arg0: bigint, arg1: PayoutStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayoutStatus(arg0, to_candid_PayoutStatus_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayoutStatus(arg0, to_candid_PayoutStatus_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AccountType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutRequest): PayoutRequest {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutStatus): PayoutStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TripRequest_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripRequest): TripRequest {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TripStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TripRequest]): TripRequest | null {
    return value.length === 0 ? null : from_candid_TripRequest_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    accountType: _AccountType;
    phone: string;
}): {
    fullName: string;
    accountType: AccountType;
    phone: string;
} {
    return {
        fullName: value.fullName,
        accountType: from_candid_AccountType_n11(_uploadFile, _downloadFile, value.accountType),
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TripStatus;
    completedAt: [] | [_Time];
    passenger: Principal;
    dropoffLocation: _Location;
    fare: [] | [bigint];
    createdAt: _Time;
    acceptedAt: [] | [_Time];
    driver: [] | [Principal];
    pickupLocation: _Location;
}): {
    id: bigint;
    status: TripStatus;
    completedAt?: Time;
    passenger: Principal;
    dropoffLocation: Location;
    fare?: bigint;
    createdAt: Time;
    acceptedAt?: Time;
    driver?: Principal;
    pickupLocation: Location;
} {
    return {
        id: value.id,
        status: from_candid_TripStatus_n19(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.completedAt)),
        passenger: value.passenger,
        dropoffLocation: from_candid_Location_n22(_uploadFile, _downloadFile, value.dropoffLocation),
        fare: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.fare)),
        createdAt: value.createdAt,
        acceptedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.acceptedAt)),
        driver: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.driver)),
        pickupLocation: from_candid_Location_n22(_uploadFile, _downloadFile, value.pickupLocation)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: [] | [number];
    description: string;
    longitude: [] | [number];
}): {
    latitude?: number;
    description: string;
    longitude?: number;
} {
    return {
        latitude: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.latitude)),
        description: value.description,
        longitude: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.longitude))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PayoutStatus;
    createdAt: _Time;
    processedAt: [] | [_Time];
    amount: bigint;
    driver: Principal;
}): {
    id: bigint;
    status: PayoutStatus;
    createdAt: Time;
    processedAt?: Time;
    amount: bigint;
    driver: Principal;
} {
    return {
        id: value.id,
        status: from_candid_PayoutStatus_n30(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        processedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.processedAt)),
        amount: value.amount,
        driver: value.driver
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    passenger: null;
} | {
    driver: null;
}): AccountType {
    return "passenger" in value ? AccountType.passenger : "driver" in value ? AccountType.driver : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    accepted: null;
}): TripStatus {
    return "cancelled" in value ? TripStatus.cancelled : "open" in value ? TripStatus.open : "completed" in value ? TripStatus.completed : "accepted" in value ? TripStatus.accepted : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    paid: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PayoutStatus {
    return "requested" in value ? PayoutStatus.requested : "paid" in value ? PayoutStatus.paid : "approved" in value ? PayoutStatus.approved : "rejected" in value ? PayoutStatus.rejected : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TripRequest>): Array<TripRequest> {
    return value.map((x)=>from_candid_TripRequest_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PayoutRequest>): Array<PayoutRequest> {
    return value.map((x)=>from_candid_PayoutRequest_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Location_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location): _Location {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PayoutStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutStatus): _PayoutStatus {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_TripStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): _TripStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    accountType: AccountType;
    phone: string;
}): {
    fullName: string;
    accountType: _AccountType;
    phone: string;
} {
    return {
        fullName: value.fullName,
        accountType: to_candid_AccountType_n33(_uploadFile, _downloadFile, value.accountType),
        phone: value.phone
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    description: string;
    longitude?: number;
}): {
    latitude: [] | [number];
    description: string;
    longitude: [] | [number];
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        description: value.description,
        longitude: value.longitude ? candid_some(value.longitude) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): {
    cancelled: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    accepted: null;
} {
    return value == TripStatus.cancelled ? {
        cancelled: null
    } : value == TripStatus.open ? {
        open: null
    } : value == TripStatus.completed ? {
        completed: null
    } : value == TripStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    passenger: null;
} | {
    driver: null;
} {
    return value == AccountType.passenger ? {
        passenger: null
    } : value == AccountType.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutStatus): {
    requested: null;
} | {
    paid: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == PayoutStatus.requested ? {
        requested: null
    } : value == PayoutStatus.paid ? {
        paid: null
    } : value == PayoutStatus.approved ? {
        approved: null
    } : value == PayoutStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
